<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Illuminate\Support\Str;
class JobPostingsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
   public function run()
    {
        $now = Carbon::now();

        $jobPostings = [
            [
                'id' => 1,
                'company_id' => 1,
                'employer_id' => 1,
                'order_id' => 1,
                'city_id' => 1,
                'email' => 'recruitment@techvietnam.com',
                'title' => 'Senior Full Stack Developer - Lương 3000$',
                'slug' => Str::slug('Senior Full Stack Developer - Lương 3000$'),
                'type' => 'Toàn thời gian',
                'category' => 'Công nghệ thông tin',
                'location' => 'Hà Nội',
                'tags' => 'php,javascript,react,nodejs',
                'description' => 'Chúng tôi đang tìm kiếm một Senior Full Stack Developer với kinh nghiệm làm việc với React, Node.js và PHP. Ứng viên sẽ tham gia vào các dự án phát triển phần mềm quy mô lớn cho khách hàng quốc tế.',
                'application_email_url' => 'https://techvietnam.com/careers',
                'closing_date' => $now->addDays(30),
                'created_at' => $now,
                'updated_at' => $now,
                'salary' => '2500$ - 3000$',
                'experience' => '5 năm trở lên',
                'rank' => 'Senior',
                'number_of_recruits' => 3,
                'sex' => 'Không yêu cầu',
                'status' => '1',
                'skills_required' => 'React, Node.js, PHP, MySQL, AWS',
                'area' => 'Hà Nội',
                'city' => 'Hà Nội',
                'isHot' => '1',
                'views' => 523,
                'service_type' => 'Tin nổi bật',
            ],
            [
                'id' => 2,
                'company_id' => 1,
                'employer_id' => 1,
                'order_id' => 1,
                'city_id' => 2,
                'email' => 'recruitment@techvietnam.com',
                'title' => 'Product Manager - Lương 2500$',
                'slug' => Str::slug('Product Manager - Lương 2500$'),
                'type' => 'Toàn thời gian',
                'category' => 'Quản lý sản phẩm',
                'location' => 'Hồ Chí Minh',
                'tags' => 'product,management,agile,scrum',
                'description' => 'Chúng tôi đang tìm kiếm một Product Manager có kinh nghiệm để quản lý và phát triển các sản phẩm công nghệ mới. Ứng viên sẽ làm việc với các nhóm kỹ thuật, thiết kế và marketing để đưa sản phẩm từ ý tưởng đến thị trường.',
                'application_email_url' => 'https://techvietnam.com/careers',
                'closing_date' => $now->addDays(25),
                'created_at' => $now,
                'updated_at' => $now,
                'salary' => '2000$ - 2500$',
                'experience' => '3 năm trở lên',
                'rank' => 'Middle Management',
                'number_of_recruits' => 1,
                'sex' => 'Không yêu cầu',
                'status' => '1',
                'skills_required' => 'Product Management, Agile, Scrum, UI/UX, Data Analysis',
                'area' => 'Hồ Chí Minh',
                'city' => 'Hồ Chí Minh',
                'isHot' => '1',
                'views' => 432,
                'service_type' => 'Tin nổi bật',
            ],
            [
                'id' => 3,
                'company_id' => 1,
                'employer_id' => 1,
                'order_id' => 1,
                'city_id' => 1,
                'email' => 'recruitment@techvietnam.com',
                'title' => 'UI/UX Designer - Lương 1800$',
                'slug' => Str::slug('UI/UX Designer - Lương 1800$'),
                'type' => 'Toàn thời gian',
                'category' => 'Thiết kế',
                'location' => 'Hà Nội',
                'tags' => 'ui,ux,design,figma,adobe',
                'description' => 'Chúng tôi đang tìm kiếm một UI/UX Designer tài năng để tham gia vào đội ngũ thiết kế sản phẩm. Ứng viên sẽ thiết kế giao diện người dùng cho các ứng dụng web và di động, tạo ra trải nghiệm người dùng tuyệt vời.',
                'application_email_url' => 'https://techvietnam.com/careers',
                'closing_date' => $now->addDays(20),
                'created_at' => $now,
                'updated_at' => $now,
                'salary' => '1500$ - 1800$',
                'experience' => '2 năm trở lên',
                'rank' => 'Middle',
                'number_of_recruits' => 2,
                'sex' => 'Không yêu cầu',
                'status' => '1',
                'skills_required' => 'Figma, Adobe XD, Sketch, UI Design, UX Research',
                'area' => 'Hà Nội',
                'city' => 'Hà Nội',
                'isHot' => '1',
                'views' => 387,
                'service_type' => 'Tin nổi bật',
            ],
            [
                'id' => 4,
                'company_id' => 1,
                'employer_id' => 1,
                'order_id' => 1,
                'city_id' => 3,
                'email' => 'recruitment@techvietnam.com',
                'title' => 'Data Scientist - Lương 2800$',
                'slug' => Str::slug('Data Scientist - Lương 2800$'),
                'type' => 'Toàn thời gian',
                'category' => 'Khoa học dữ liệu',
                'location' => 'Đà Nẵng',
                'tags' => 'python,data,machine-learning,ai',
                'description' => 'Chúng tôi đang tìm kiếm một Data Scientist có kinh nghiệm để phân tích dữ liệu và xây dựng các mô hình machine learning. Ứng viên sẽ làm việc với lượng dữ liệu lớn để tìm ra các insights và phát triển các giải pháp AI.',
                'application_email_url' => 'https://techvietnam.com/careers',
                'closing_date' => $now->addDays(15),
                'created_at' => $now,
                'updated_at' => $now,
                'salary' => '2300$ - 2800$',
                'experience' => '3 năm trở lên',
                'rank' => 'Senior',
                'number_of_recruits' => 2,
                'sex' => 'Không yêu cầu',
                'status' => '1',
                'skills_required' => 'Python, R, Machine Learning, TensorFlow, SQL',
                'area' => 'Đà Nẵng',
                'city' => 'Đà Nẵng',
                'isHot' => '1',
                'views' => 412,
                'service_type' => 'Tin nổi bật',
            ],
            [
                'id' => 5,
                'company_id' => 1,
                'employer_id' => 1,
                'order_id' => 1,
                'city_id' => 2,
                'email' => 'recruitment@techvietnam.com',
                'title' => 'Mobile Developer (React Native) - Lương 2200$',
                'slug' => Str::slug('Mobile Developer (React Native) - Lương 2200$'),
                'type' => 'Toàn thời gian',
                'category' => 'Phát triển ứng dụng di động',
                'location' => 'Hồ Chí Minh',
                'tags' => 'react-native,javascript,mobile,ios,android',
                'description' => 'Chúng tôi đang tìm kiếm một Mobile Developer với kinh nghiệm về React Native để phát triển các ứng dụng di động đa nền tảng. Ứng viên sẽ tham gia vào đội ngũ phát triển và đóng góp vào tất cả các giai đoạn của chu kỳ phát triển phần mềm.',
                'application_email_url' => 'https://techvietnam.com/careers',
                'closing_date' => $now->addDays(10),
                'created_at' => $now,
                'updated_at' => $now,
                'salary' => '1800$ - 2200$',
                'experience' => '2 năm trở lên',
                'rank' => 'Middle',
                'number_of_recruits' => 3,
                'sex' => 'Không yêu cầu',
                'status' => '1',
                'skills_required' => 'React Native, JavaScript, Redux, iOS, Android',
                'area' => 'Hồ Chí Minh',
                'city' => 'Hồ Chí Minh',
                'isHot' => '1',
                'views' => 465,
                'service_type' => 'Tin nổi bật',
            ],
        ];

        DB::table('job_postings')->insert($jobPostings);
    }
}
